### ISSUE TITLE
nRF52 kick start

### ISSUE THREAD

**Issue by rosek86** [NordicSemiconductor/pc-ble-driver-js#13]
Hi,

I'm trying to compile sd2.0 driver and try this with nRF52 dev kit. I've compiled the driver correctly but I get the following error when I try to run an example script. Can you please give me a hint how to fix that? 

Regards,
Krzysztof

    pc-ble-driver-js-update-driver-sd2.0>"C:\Program Files (x86)\nodejs\node.exe" examples\example_scan.js
    pc-ble-driver-js-update-driver-sd2.0\node_modules\bindings\bindings.js:83
        throw e
        ^

    Error: Module version mismatch. Expected 47, got 46.
        at Error (native)
        at Object.Module._extensions..node (module.js:440:18)
        at Module.load (module.js:357:32)
        at Function.Module._load (module.js:314:12)
        at Module.require (module.js:367:17)
        at require (internal/module.js:16:19)
        at bindings (C:\Users\Krzysztof Rosinski\Desktop\pc-ble-driver-js-update-driver-sd2.0\node_modules\bindings\bindings.js:76:44)
        at Object.<anonymous> (C:\Users\Krzysztof Rosinski\Desktop\pc-ble-driver-js-update-driver-sd2.0\index.js:13:33)
        at Module._compile (module.js:413:34)
        at Object.Module._extensions..js (module.js:422:10)

**Comment by rosek86** [comment]
Actually, I solved my issue now... I've compiled driver by using 64-bit npm and then was trying to run script with 32-bit node.

"C:\Program Files (x86)\nodejs\npm" install

fixed this.
