### ISSUE TITLE
Module error on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by lbabaly** [NordicSemiconductor/pc-ble-driver-js#4]
Hello,
I tried to play with it on Ubuntu 14.04 LTS but after compiling everything successfully I got the following error message when I started one of the examples:

user:~/nordicjs/pc-ble-driver-js-master$ node simplescan.js
/home/user/nordicjs/pc-ble-driver-js-master/node_modules/bindings/bindings.js:83
        throw e
        ^

**Error: Module version mismatch. Expected 47, got 46.**
    at Error (native)
    at Object.Module._extensions..node (module.js:440:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at bindings (/home/user/nordicjs/pc-ble-driver-js-master/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/user/nordicjs/pc-ble-driver-js-master/simplescan.js:3:33)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
 
Any idea what could be the problem?
Thank you,

Laszlo

**Comment by kenr** [comment]
Hi,

You have to set the environment variable npm_config_target to the version of nodejs that you have installed. You can see the default values in https://github.com/NordicSemiconductor/pc-ble-driver-js/blob/master/build.js#L17
